### ISSUE TITLE
Bug: Responsive UI Issues with Background Image

### ISSUE THREAD

**Issue by Tamanna225** [Ramsey99/fest-registration#11]
There is problem with the UI responsiveness, specifically related to the background image in the project.

**Expected Behavior:**
The background image should cover the entire viewport, maintaining its presence even when scrolling horizontally or vertically.

**Actual Behavior:**
When the screen size decreases, the background image does not cover the entire screen properly and may appear to repeat or become misaligned.

![Screenshot 2024-09-27 174614](https://github.com/user-attachments/assets/ce00cc0b-7c9f-40e4-910b-b73b5267530b)

**Comment by soumyajit254** [comment]
I would like to contribute to this issue. Please assign it to me
