### ISSUE TITLE
See Details Page Enhancement: Improve UI Theme, User Friendliness and Upgrade Navbar

### ISSUE THREAD

**Issue by Tamanna225** [Ramsey99/fest-registration#14]
This issue focuses on implementing a similar theme for the see_details page as Index.html to enhance user experience. The goal is to make the page more user-friendly through better design and improved CSS styles.

**Consistent Theme:**
Apply a unified color scheme that aligns with the overall project design

**Updated CSS:**
-Revise CSS styles to enhance visual appeal, including improved layout, spacing, and engaging UI elements.

**Improved Navbar:**
-Redesign the navbar to include additional elements beyond "Home," creating clear navigation options for users.
-Ensure the navbar is visually aligned with the new theme and enhances overall usability.

Please Assign me this Issue as I am eager to enhance this Project

**Comment by soumyajit254** [comment]
hi , i would like to contribute to this issue! please assign it to me

**Comment by Albert-2** [comment]
hey @Tamanna225 
I would like to contribute to this issue, can you please assign me the same
Thank You...!!

**Comment by AtharvaTayade1** [comment]
Hiii!
Can you assign me the issue, I would like to contribute to it...
Thank you!!

**Comment by sakship2005** [comment]
Hi! I would like to work on this issue. It would be great if you could assign me this issue.

**Comment by Tamanna225** [comment]
@Ramsey99 Can you please add the labels of wob
