### ISSUE TITLE
Index.html Update: Implement Hover Effects and Form Validation Improvements

### ISSUE THREAD

**Issue by Tamanna225** [Ramsey99/fest-registration#15]
This issue involves updating the index.html page to include hover effects and enhance form validation. The goal is to improve user interaction and ensure validation messages are displayed near the relevant fields.

-Implement hover effects on buttons and input fields for better interactivity.
-Ensure form validation checks are in place and display error messages near the respective fields instead of below the submit button.

Please assign me this issue as I am eager to enhance this Project

**Comment by soumyajit254** [comment]
hi , i would like to contribute to this issue! please assign it to me

**Comment by Albert-2** [comment]
hey @Tamanna225 
I would like to contribute to this issue, can you please assign me the same
Thank You...!!
