### ISSUE TITLE
Feature Implementation : Profile Update Feature Implementation

### ISSUE THREAD

**Issue by Varsha-1605** [Ramsey99/fest-registration#33]
# Description
We can implement a profile update feature for our event registration system. This feature allows users to modify their existing information and update their profile pictures. 

### 1. Update `see_details.html`:
   - Add an "Update" button for each registered candidate
   - Modify the layout to accommodate the new action column

### 2. Modify `app.py`:
   - Add a new route `/update_profile/<roll>` to handle both GET and POST requests
   - Implement logic to fetch existing profile data and process update submissions

### 3. Create `update_profile.html`:
   - Develop a new template for the profile update form
   - Pre-fill existing user data in the form fields
   - Allow updating all fields including profile picture

### 4. Update `event_database.sql`:
   - Add a new stored procedure `update_profile` to handle profile updates in the database

**Comment by snehas-05** [comment]
Heyy @ramsey99 could you please assign this task to me? I would love to do the task- Feature Implementation : Profile Update Feature Implementation

**Comment by Varsha-1605** [comment]
@Ramsey99 I can see as of now no one has raised this issue, could you please explain me the reason behind closing this issue?

**Comment by Varsha-1605** [comment]
@snehas-05 
 I wanted to let you know that I've already worked on that feature and implemented it. If it's alright with you, I would appreciate the opportunity to continue focusing on this aspect.
