### ISSUE TITLE
UI/UX Improvements and Feature Enhancements for Event Registration Form

### ISSUE THREAD

**Issue by TusharNaugain** [Ramsey99/fest-registration#57]
![Uploading Screenshot 2024-10-19 at 2.27.08 AM.png…]()
UI Design and Layout:

The form layout is basic and lacks proper alignment and spacing, making it look cluttered and unappealing.
Buttons are styled the same, without differentiation for their purpose (Submit, Save, Load).
The heading "Grand Event Celebration" lacks proper styling, making it appear too simple.
Form Styling:

Input fields lack consistent padding and borders, leading to a less polished appearance.
The select dropdowns for "Stream" and "Event" are basic and could benefit from enhanced design (e.g., custom dropdown icons or more engaging styles).
Error Handling:

Error messages aren't placed in a user-friendly manner. They are appended at the end of the form rather than appearing directly under the relevant fields.
The error styling (like adding a red border or tooltip) is missing. It needs to be more visually noticeable.

Missing Features ----> 
Responsive Design: The form is not optimized for mobile devices. It may break or look misaligned on smaller screens due to the lack of responsive design.
Form Validation Enhancements: Currently, the form only checks the "Phone number" length, but it could be further validated for digits-only input.
Upload Image Preview: After the user uploads a profile picture, there is no preview, which is a common feature in modern registration forms.
Accessibility:

No alt text for images or ARIA attributes to ensure accessibility for screen readers.
Lack of keyboard navigation features for users relying on keyboards.
UI Enhancements:

Missing hover effects for buttons, enhancing the user experience.
The "QR Code" generation section is under-utilized. It should have some clear indication or styling to highlight that the QR code will appear there.

**Comment by NITYANIT** [comment]
can you assign me this issue.i have worked on this before and im a beginner.

**Comment by TusharNaugain** [comment]
@Ramsey99 can youplease
 add on the label of hactoberfest and Gssoc!
